# ========= MineLC Configuración =========
#
# YAML hecho por ElBuenAnvita
# El plugin hecho por Leo018, modificado por obed_007 y por ElBuenAnvita, creo que Cemarquez también lo modificó.
# Por favor mantener siempre un archivo de respaldo tipo .old_yml en caso de que hagas una pelotudez y se reinicie el archivo por error.
# No cambiar la version-config a menos que sepas lo que estás haciendo.
# No realizar NINGÚN cambio bajo la supervisión de un desarrollador (developer).
#
# ========= Fin MineLC Configuración =========
version-config: 1

permisos: # Si se quiere colocar un permiso NEGATIVO, colocar "-" al inicio. Ej: "-essentials.me", esto negará rotundamente el permiso al usuario.
  default:
    - "default.general"
    - "plotme.use.remove"
    - "plotme.use.add"
    - "plots.plot.1"
    - "plotme.use"
    - "plots.visit"
    - "plots.visit.other"
    - "plots.set"
    - "plots.set.flag"
    - "plots.permpack.basic"
    - "plots.permpack.basicflags"
    - "plots.set.flag.use.*"
    - "marry.default"
    - "plots.permpack.basicinbox"
    - "menus.principal"
    - "headdb.online.hide"
    - "essentials.balance"
    - "essentials.pay"
    - "margaret.partnership"
    - "margaret.partnership.*"
    - "margaret.gender"
    - "margaret.setting"
    - "margaret.proposal"
    - "margaret.list"
    - "margaret.partnership.home.*"
  vip:
    - "vip.general"
    - "plots.plot.10"
    - "plots.merge.4"
    - "plots.music"
    - "plots.set.flag.music.*"
    - "plots.set.flag.titles.*"
    - "worldedit.brush.sphere"
    - "worldedit.brush.cylinder"
    - "worldedit.brush.clipboard"
    - "worldedit.brush.smooth"
    - "worldedit.brush.ex"
    - "worldedit.brush.gravity"
    - "worldedit.brush.butcher"
    - "worldedit.wand"
    - "worldedit.clipboard.copy"
    - "worldedit.clipboard.cut"
    - "worldedit.clipboard.paste"
    - "worldedit.generation.cylinder"
    - "worldedit.generation.sphere"
    - "worldedit.generation.pyramid"
    - "worldedit.history.undo"
    - "worldedit.history.redo"
    - "worldedit.region.walls"
    - "worldedit.region.naturalize"
    - "worldedit.region.set"
    - "worldedit.wand.toggle"
    - "worldedit.selection.pos"
    - "worldedit.superpickaxe"
    - "worldedit.region.replace"
    - "worldedit.selection.expand"
    - "worldedit.clipboard.rotate"
    - "worldedit.clipboard.flip"
    - "fawe.permpack.basic"
    - "fawe.plotsquared"
    - "fawe.plotsquared.member"
    - "menus.vip"
    - "vip.world"
    - "petblocks.gui"
    - "petblocks.command.use"
    - "petblocks.command.toggle"
    - "petblocks.command.call"
    - "headdb.open"
    - "headdb.category.alphabet"
    - "headdb.category.animals"
    - "headdb.category.blocks"
    - "headdb.category.decoration"
    - "headdb.category.food_drinks"
    - "headdb.category.humans"
    - "headdb.category.humanoid"
    - "headdb.category.miscellaneous"
    - "headdb.category.monsters"
    - "headdb.category.plants"
    - "headdb.allow.buy.alphabet"
    - "headdb.allow.buy.animals"
    - "headdb.allow.buy.blocks"
    - "headdb.allow.buy.decoration"
    - "headdb.allow.buy.food_drinks"
    - "headdb.allow.buy.humans"
    - "headdb.allow.buy.humanoid"
    - "headdb.allow.buy.miscellaneous"
    - "headdb.allow.buy.monsters"
    - "headdb.allow.buy.plants"
  svip:
    - "svip.general"
    - "headdb.phead"
    - "petblocks.command.rename"
    - "plots.plot.15"
    - "worldedit.clipboard.rotate"
  elite:
    - "elite.general"
    - "plots.plot.30"
    - "petblocks.command.customhead"
    - "plots.set.border"
  ruby:
    - "ruby.general"
    - "plots.plot.45"
  youtuber:
    - "yt.general"
  ayudante:
    - "ayudante.general"
  mod:
    - "mod.general"
  admod:
    - "admod.general" # NO SE USA. MISMOS DE ADMIN. POR FAVOR NO REMOVER.
  admin:
    - "admin.general"
    - "*"
    - "bukkit.*"
    - "minecraft.*"
    - "-Bikes.overrideWorld"
    - "-Cars.overrideWorld"
    - "-Trains.overrideWorld"
    - "-Rafts.overrideWorld"
    - "-Planes.overrideWorld"
    - "-Parachutes.overrideWorld"
    - "-Helicopters.overrideWorld"
    - "-Tanks.overrideWorld"
    - "-Submarines.overrideWorld"
    - "-Brooms.overrideWorld"
    - "-HoverBikes.overrideWorld"
    - "-Drills.overrideWorld"
    - "-SportBikes.overrideWorld"
    - "-RacingCars.overrideWorld"
    - "-Tractors.overrideWorld"
    - "-Bikes.overrideRemoveOnDismount"
    - "-Cars.overrideRemoveOnDismount"
    - "-Trains.overrideRemoveOnDismount"
    - "-Rafts.overrideRemoveOnDismount"
    - "-Planes.overrideRemoveOnDismount"
    - "-Parachutes.overrideRemoveOnDismount"
    - "-Helicopters.overrideRemoveOnDismount"
    - "-Tanks.overrideRemoveOnDismount"
    - "-Submarines.overrideRemoveOnDismount"
    - "-Brooms.overrideRemoveOnDismount"
    - "-HoverBikes.overrideRemoveOnDismount"
    - "-Drills.overrideRemoveOnDismount"
    - "-SportBikes.overrideRemoveOnDismount"
    - "-RacingCars.overrideRemoveOnDismount"
    - "-Tractors.overrideRemoveOnDismount"
    - "-itemjoin.bypass.inventorymodify"
    - "petblocks.admin.command.pets"
    - "petblocks.admin.command.reload"
    - "-perworldinventory.bypass.gamemode"
    - "-perworldinventory.bypass.world"
  owner:
    - "owner.general" # NO SE USA. MISMOS DE ADMIN. POR FAVOR NO REMOVER.

mensajes: # Espacios aparte con \n
  header: "&7 \n&8&m========&f&l[ &b&lCreativo&f&l ]&8&m========\n&8  " # Lo que aparecerá encima de la lista de los usuarios
  footer: "&7 \n&8&m========&f&l[ &6&lWWW.MINELC.NET &f&l]&8&m========\n&8- &a&lJugando &8- \n&8- &e&lPLAY.MINELC.NET &8-\n&8  " # Lo que aparecerá debajo de la lista de los usuarios
  bienvenida: # Espero implementar esto pronto. No funciona aún.
    - "&7&m-------------------"
    - "&3&lMine&6&lLC &b&lNetwork"
    - "&b&lCreativo"
    - "&f¡Bienvenido, $user$!"
    - "&7&m------------------"
  scoreboard:
    # Funciona con PlaceholderAPI si está instalado y si la expansión lo está igual.
    # LC tiene expansión propia de igual modo.
    # Una línea NO puede ser igual que la otra. Si se necesita espaciar, deje espacios distintos en cada caso.
    - "&7&m+-----------------------+"
    - "&8» &fUsuario: &7%player_name%"
    - "      "
    - "&8» &fDinero: &a$%vault_eco_balance_fixed%"
    - "&8» &fRango: %lc_rankcolorsignorehidden%"
    - "    "
    - "&8» &fMundo: $mundo$"
    - "&8» &fPlot: $current-plot-formatted$"
    - "  "
    - "&8» &fConectados: &3$online$&7/&3$maxuser$"
    - "&8» &fIP: &eplay.minelc.net"
    - "&7&m+------------------------+"

  # Títulos cuando un usuario entra al servidor. Se tardan como 2 ticks en aparecer.
  titles-title: "&aCreativo" # Título
  titles-subtitle: "&ewww.minelc.net" # Subtítulo

ubicaciones:
  spawn:
    vip:
      x: 2007 # Pred. 2007
      y: 162 # Pred. 162
      z: 2009 # Pred. 2009
    plots:
      x: 0 # Pred. 0
      y: 73 # Pred 73
      z: 0 # Pred 0

admod-user: "_iTzOver_" # Usuario que debería tener ADMOD. Usar con cautela. No puede estar vacío, pues le daría ADMOD a ElBuenAnvita.

no-standing-plot-message: "&6Ninguna" # Esto aparecerá cuando el usuario no ande dentro de una parcela.

# Esto es como el usuario en el scoreboard vería el mundo en el que está
vip-world: "&b&lVIP" # Si está en el mundo VIP
normal-world: "&cParcelas" # Si está en el mundo "parcelas"
unknown-world: "&9&oNarnia" # Si está en otro mundo distinto al vip o parcelas.

save-location-in-vip: false # Si el usuario se desconecta estando en VIP, ¿se deberá guardar o no su ubicación? false es predeterminado.
# prevent-nonvip-users-in-vip: true # Si está activado, usuarios no podrán entrar al mundo VIP, si intentan hacerlo, les aparecerá un letrero diciendo que no son VIP.
prevent-nonvip-users-from-claim-plot-in-vip: true # Prevenir que los usuarios sin el permiso "vip.world" compren/claimeen una parcela. PRONTO

cooldown-time-mincecart-or-boat: 6000 # En milisegundos

vip-deny-titulo: "&4&lNo eres VIP" # Título
vip-deny-subtitulo: "&cNo puedes ingresar a este mundo" # Subtitulo

marry-a-prueba-de-tontos: true # Si está activado y alguien hace /marry <argumento>, enviará un mensaje corrigiendolo acerca de como se envía correctamente una invitación.
marry-correccion-message: "&7[&3MG&7] &cEnvía una propuesta de pareja a alguien usando &e/mg prop send <usuario>&c." # Mensaje que aparecerá si lo de arriba pasa y está activado

debug: false # Debug. Tampoco funciona