name: MineLC_Creativo
main: com.minelc.Creativo.CreativolMain
version: 1.5-RELASE
api-version: 1.15
authors: [Leo018, obed_007, ElBuenAnvita]
depend: [MineLC_CORE, PlaceholderAPI, PlotSquared]
commands:
   minelc:
      description: MineLC comando.
      usage: /<command> [args]
   gamemode:
      description: Cambia tu modo de juego.
      usage: /<command> [args]
      aliases: [gm]
   fly:
      description: Habilita o deshabilita el vuelo.
      usage: /<command> [args]
   teleport:
      description: Teletranspórtate a un usuario.
      usage: /<command> [args]
      aliases: [tp]
   teleportworld:
      description: teleportac.
      usage: /<command> [args]
      aliases: [tpworld, tpw]
   spawn:
      description: Ve al punto de aparición inicial.
      usage: /<command> [args]
      aliases: [inicio, regresar]
   nick:
      description: Colocate un nombre de usuario distinto.
      usage: /<command> [args]
   realname:
      description: Conoce el nombre verdadero de alguien.
      usage: /<command> [args]
   report:
     description: Habla con el staff en línea de Creativo.
     aliases: [helpop, reportar]
   mem:
     description: info
   vanish:
      description: vanish.
      usage: /<command> [args]
      aliases: [v]
   tpa:
     description: Pídele a un usuario el permiso de teletransportarse hacia él.
   sit:
     description: sit
   tpaccept:
     description: Acepta una petición de tpa.
     aliases: [tpasi]
   tpdeny:
     description: Niega una petición de tpa.
     aliases: [tpano]
   s:
     description: s
   tphere:
     description: Forza a alguien a teletransportarse hacia ti.
     aliases: teleporthere
   near:
     description: Encuentra los jugadores más cercanos a ti
   tell:
     description: Envía un mensaje privado a alguien
     aliases: [w, whisper, msg]